CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       email VARCHAR(255) NOT NULL,

                       password VARCHAR(255) NOT NULL,

                       role VARCHAR(255) NOT NULL,

                       created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

                       CONSTRAINT uk_users_email UNIQUE (email)
);


CREATE TABLE documents (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           original_filename VARCHAR(255) NOT NULL,

                           status VARCHAR(255) NOT NULL,

                           created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

                           user_id BIGINT NOT NULL,

                           CONSTRAINT fk_documents_user
                               FOREIGN KEY (user_id)
                                   REFERENCES users(id)
);


CREATE INDEX idx_documents_user_id
    ON documents(user_id);